[window]
opacity = 1.0
decorations = "full"
startup_mode = "Windowed"

[font]
size=13.5

[font.normal]
family="monospace"
style="Regular"

[font.bold]
family="monospace"
style="Bold"

[colors]
[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[colors.cursor]
text = "#272822"
cursor = "#f8f8f2"

[colors.selection]
text = "#272822"
background = "#49483e"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"

[cursor]
style = "Block"
